---

- name: Add OpenVPN repo GPG key
  ansible.builtin.apt_key:
    id: E158C569
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
  when: openvpn_use_external_repo | bool

- name: Add OpenVPN repo sources
  ansible.builtin.apt_repository:
    filename: openvpn
    repo: deb http://swupdate.openvpn.net/apt "{{ ansible_lsb.codename }}" main
  when: openvpn_use_external_repo | bool

- name: Install requirements
  ansible.builtin.apt:
    name: "{{ requirements }}"
    update_cache: true
    force: true
  vars:
    requirements:
      - openvpn
      - udev
      - openssl
      - zip

- name: Install PAM dependencies
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    force: true
  when: openvpn_use_pam_users | length > 0
  vars:
    dependencies:
      - libpam-pwdfile
      - python-passlib

- name: Install LDAP dependencies
  ansible.builtin.apt:
    name: openvpn-auth-ldap
    force: true
  when: openvpn_use_ldap | bool

- name: Install bridge dependencies
  ansible.builtin.apt:
    name: bridge-utils
  when: openvpn_bridge | bool
