---

- name: Generate Clients configurations for each user per endpoint
  template: src=client.conf.j2 dest="{{openvpn_keydir}}/{{user}}.{{item}}.ovpn"
  with_items: "{{ openvpn_endpoints }}"
  notify: openvpn pack clients
  register: openvpn_clients_changed

