---

- name: Setup bridge
  when: openvpn_bridge
  template:
    src: bridge-interface.j2
    dest: "/etc/network/interfaces.d/{{ openvpn_dev }}"
  register: bridge
  tags: [bridge]

- name: Restart networking
  service: name=networking state=restarted
  when: openvpn_bridge and bridge|changed
  tags: [bridge]

- file:
    path: "/etc/network/interfaces.d/{{ openvpn_dev }}"
    state: absent
  when: not openvpn_bridge
  tags: [bridge]
