---

- name: Install requirements
  yum:
    name: "{{ requirements }}"
    update_cache: true
  vars:
    requirements:
      - openvpn
      - openssl
      - zip

- name: Install easy-rsa package
  yum:
    name: easy-rsa
  when: openvpn_use_system_easyrsa | bool
